### PR TITLE
Fix publicPath not being respected.

### PR DESCRIPTION
**Pull request by satazor**
See #3

### CODE REVIEW

**Comment by bensampaio** [comment]
Thanks a lot for the contribution @satazor. I did forget to take into account this case, since in my projects I always use `/` as the `publicPath`. However I would like this to be done differently, I think `publicPath` should be passed into `getUrlToSymbol ` and `getUrlToView ` as a URL prefix instead of concatenating it to the result of those functions.

If you change that I will merge this PR. Thanks!

**Comment by satazor** [comment]
@bensampaio new signatures will be `getUrlToSymbol(publicPath)` and `getUrlToView(publicPath)` correct?

**Comment by bensampaio** [comment]
Yes, correct!

**Comment by satazor** [comment]
@bensampaio do you want the `publicPath` right trimming of `/` inside these functions? Or we assume that is already trimmed?

**Comment by bensampaio** [comment]
@satazor I think it would make more sense to trim it inside the function, indeed. Thanks!

**Comment by satazor** [comment]
@bensampaio PR updated. 

Regarding doc blocks, `publicPath` is optional and I signaled that with `[]`. Is it correct?

**Comment by bensampaio** [comment]
@satazor, yes that's correct! Nice job. Thanks a lot! I will merge and publish it to npm later today.

Obrigado :p

**Comment by bensampaio** [comment]
I just published `1.0.2` to npm :)

**Comment by satazor** [comment]
Obrigado :)

**Pull request merged**
