### PR TITLE
Change icon id on add to sprite

### PR DESCRIPTION
**Pull request by witem**
It need for allow using some svg loaderes, as example: https://www.npmjs.com/package/svg-transform-loader . With this loader one svg file may have different content, and if use in iconName `[hash]` it allow to work well.

### CODE REVIEW

**Comment by bensampaio** [comment]
@witem can you provide a bit more details? How are you using `svg-transform-loader`? What goes wrong when you use it?

**Comment by witem** [comment]
Example:
```
.icon-white {background-image: url(img.svg?fill=#fff)}
.icon-green {background-image: url(img.svg?fill=#0f0)}
.icon-blue {background-image: url(img.svg?fill=#00f)}
```

It use one file on disk but generate 3 different file after build with different content. And need update your addIcon logic to check file content hash also. Plugin notes: https://www.npmjs.com/package/svg-transform-loader#usage-with-file-loader

P.S. now your plugin save only first file and ignore other, because not check file content hash

**Comment by witem** [comment]
@bensampaio you merge this PR?

**Comment by bensampaio** [comment]
@witem can you have a look at the solution I propose in https://github.com/karify/external-svg-sprite-loader/pull/56? I believe this solution would serve your case better. Let me know if it works for you.

**Pull request closed without merging**
